### ISSUE TITLE
Indexing issue

### ISSUE THREAD

**Issue by r5b9** [draffter/FollowFunctionPHP#1]
Hi

Nothing is happening when I press ctrl+k and ctrl+i.
If I press ctrl+k for few times, it cuts the lines off.

**Comment by draffter** [comment]
Hi!

Please open terminal in sublime (ctrl+`) and press ctrl+k ctrl+i 
If something went wrong, you will see the error. Please send me this.

And one more thing. If you see on terminal message like "could not create file (...) Followfunctionphp" or something like that, update plugin from repo.

greetings!

**Comment by r5b9** [comment]
Hi!

Thanks, but when I do this, I get:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./Buildindexffphp.py", line 23, in run
AttributeError: 'BuildindexffphpCommand' object has no attribute 'pathForDB'

**Comment by draffter** [comment]
Are you using sublime on Windows or Linux?
and in which directory have you installed plugin?
Its very important informations.

**Comment by r5b9** [comment]
It is here ~/.config/sublime-text-2/Packages/FollowFunctionPHP/
What is windows?

**Comment by draffter** [comment]
Thank you for your issue. I uploaded new version on GIT. if U're using Package Control for sublime, u have to wait couple of hour for update PC repository.

Please confirm, if my update works.

**Comment by r5b9** [comment]
Got another issue indexing files:

theme loaded
loading pointer bindings
Exception in thread Thread-16:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./Buildindexffphp.py", line 118, in run
  File "./Buildindexffphp.py", line 92, in find
  File "./Buildindexffphp.py", line 76, in grep
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)

**Comment by draffter** [comment]
Hi!

Sorry for delay.
Now should works fine.
